config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  # now we can create our own show action since we used except up
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # added route in data management section - scope
  get 'portfolios/angular-items', to: 'portfolios#angular'

  # get 'pages/home'
  root to: 'pages#home'

  # get 'pages/about'
  get 'about-me', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  get 'tech-news', to: 'pages#tech_news'

  post 'message', to: 'pages#message'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/blog.rb
class Blog < ApplicationRecord

  enum status: { draft: 0, published: 1 }
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id, :main_image

  mount_uploader :main_image, PortfolioUploader

  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy

  default_scope { order(created_at: :desc) }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:create, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.page(params[:page]).per(5)
    else
      @blogs = Blog.published.page(params[:page]).per(5)
    end
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
    
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page!!!"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_path, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.published?
      @blog.draft!
    else
      @blog.published!
    end

    redirect_to blogs_path, notice: "Post status has been updated to #{@blog.status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body, :topic_id, :status, :main_image)
  end

  def set_sidebar_topics
    if logged_in?(:site_admin)
      @side_bar_topics = Topic.with_blogs(1)
    else
      @side_bar_topics = Topic.with_blogs(0)
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", widht: 20
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language || :text).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/blogs/_admin_actions.html.erb
<div style="margin-bottom: 20px">
  <% if logged_in?(:site_admin) %>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        <%= link_to blog.status.capitalize, toggle_status_blog_path(blog), class: "btn btn-sm btn-outline-secondary" %>
        <%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-sm btn-outline-secondary" %>
        <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure want to delete this blog post?' }, class: "btn btn-sm btn-outline-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) + " ago | by " + blog.user.name %> </p>

  <%= render partial: "blogs/admin_actions", locals: {blog: blog } %>

  <div>
    <%= image_tag blog.main_image.to_s, width: "100%" %>
  </div>

  <p><%= markdown blog.body %></p>

  <hr>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title, 
                                  {
                                    include_blank: true
                                  },class: "form-control") 
                                  %>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>

    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="custom-file">
    <input type="file" class="custom-file-input" id=<%= form.file_field :main_image %>
    <label class="custom-file-label" for="validatedCustomFile">Upload a main image file...</label>
  </div>
  
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", rows: "20" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<%= render "shared/blog_masthead" %>
<div class="col-md-8 blog-main">
    <%= render @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">

  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main blog-show">

  <h1><%= @blog.title %></h1>

  <b><p class="breadcrumb-item active"><%= link_to @blog.topic.title, @blog.topic %></p></b>

  <nav aria-label="breadcrumb" class="breadcrumb ">
    <%= link_to "Home", root_path, class: "breadcrumb-item" %>
    <%= link_to @blog.topic.title, @blog.topic, class: "breadcrumb-item" %>
    <span class="breadcrumb-item active"><%= @blog.title %></span>

    <% if logged_in?(:site_admin) %>
      <span class="breadcrumb-item float-right">
        <%= link_to fa_icon("pencil-square-o"), edit_blog_path(@blog) %>
      </span>
      <span class="breadcrumb-item float-right">
        <%= link_to fa_icon("trash"), @blog, method: :delete, data: { confirm: 'Are you sure want to delete this blog post?' } %>
      </span>
    <% end %>
  </nav>

  <div>
    <%= image_tag @blog.main_image.to_s, width: "100%" %>
  </div>

  <p><%= markdown @blog.body %></p>

  <hr>
  
  <%= render "comments/comment_form" %>

  <br>

  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>

  <br>
</div>