config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  # now we can create our own show action since we used except up
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # added route in data management section - scope
  get 'portfolios/angular-items', to: 'portfolios#angular'

  # get 'pages/home'
  root to: 'pages#home'

  # get 'pages/about'
  get 'about-me', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  get 'tech-news', to: 'pages#tech_news'

  post 'message', to: 'pages#message'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs["name"].blank? }

  validates_presence_of :title, :body

  mount_uploader :main_image, PortfolioUploader
  mount_uploader :thumb_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_portfolio
      @portfolio_item = Portfolio.find(params[:id])
    end
  
    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:id, :name, :_destroy]
                                        )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img != ""
      img
    elsif type == 'thumb'
      image_generator(height: "350", width: "200")
    elsif type == 'main'
      image_generator(height: "600", width: "400")
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>
  <% if portfolio_item.errors.any? %>
    <% portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row portfolio-form">
    <div class="col-md-6">
      <div class="form-group">
        <b><%= f.label :title %></b>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <b><%= f.label :subtitle %></b>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="custom-file">
        <input type="file" class="custom-file-input" id=<%= f.file_field :main_image %>
        <label class="custom-file-label" for="validatedCustomFile">Upload a main image file...</label>
      </div>

      <br>
      <br>

      <div class="custom-file">
        <input type="file" class="custom-file-input" id=<%=f.file_field :thumb_image %>
        <label class="custom-file-label" for="validatedCustomFile">Upload a thumb image file...</label>
      </div>

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <b><%= f.label :body %></b>
        <%= f.text_area :body, class: "form-control", rows: 12 %>
      </div>
    </div>
  </div>
  <hr>
    <div class="col-md-6">
      <h3>Technologies Used:</h3>
      <div>
        <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
        <% end %>
        <div><%= link_to_add_association "Add Technology", f, :technologies %></div>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 box-shadow">
    <%= link_to portfolio_show_path(portfolio_item.id) do %>
    <%= image_tag portfolio_img(portfolio_item.thumb_image.to_s, "thumb"), width: "100%", height: "100%" %>
    <% end %>
    <div class="card-body">
      <p class="card-text">
        <span><%= portfolio_item.title %></span> |
        <span><%= portfolio_item.subtitle %></span>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", portfolio_show_path(portfolio_item.id), class: "btn btn-sm btn-outline-secondary"  %>
          <% if logged_in?(:site_admin) %>
          <%= link_to "Edit", edit_portfolio_path(portfolio_item.id), class: "btn btn-sm btn-outline-secondary" %>
          <%= link_to "Delete", portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure want to delete this portfolio item?' }, class: "btn btn-sm btn-outline-danger" %>
          <% end %>
        </div>
        <small class="text-muted"><%= distance_of_time_in_words(portfolio_item.created_at, Time.now) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association "Remove Technology", f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin)%>

<% @angular_portfolio_items.each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)	%></p>
	<p><%= portfolio_item.subtitle	%></p>
	<p><%= portfolio_item.body	%></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?	%>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
	<%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure want to delete this portfolio item?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h2>Edit Portfolio Item:</h2>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<%= render "shared/portfolio_masthead" %>

<div class="album py-5 bg-light">
  <div class="container">
    
    <%= source_helper("alert alert-warning") %>

    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: "portfolio_item", collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h2>Create new Portfolio Item:</h2>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-style">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image.to_s, "main"), width: "100%", height: "100%" %>
    </div>
    <div class="col-md-5"> 
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%=  @portfolio_item.body %></p>

      <hr>

      <h2>Technologies Used:</h2>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
      <% if logged_in?(:site_admin) %>
        <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: "btn btn-sm btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>