config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  # now we can create our own show action since we used except up
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # added route in data management section - scope
  get 'portfolios/angular-items', to: 'portfolios#angular'

  # get 'pages/home'
  root to: 'pages#home'

  # get 'pages/about'
  get 'about-me', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  get 'tech-news', to: 'pages#tech_news'

  post 'message', to: 'pages#message'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot mt-auto">
  <div class="inner">
    <p> <%= copyright_generator %> </p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Jamal AWAD</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= navbar_helper('nav-link', 'span') %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <a href="http://www.jaywad.com">Jaywad.com </a><%= copyright_generator %>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">My Blog</h1>
    <p class="lead my-3">Tips, Tricks and Techniques on everything and mainly on web development. This website is created, written and maintained by <b class="font-weight-bold">me</b> and a team of swell people</p>
    <%= link_to 'Write new Blog |', new_blog_path if logged_in?(:site_admin) %>
    <%= link_to "Topics", topics_path %>
    <p class="lead mb-0"><a href="/blogs" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Jamal AWAD</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= navbar_helper('nav-link', 'li') %>
    </ul>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar blog-show">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0"><em>We are what we repeatedly do, so then excellence is not an act, but a habit. The more time you put into something, the better results you'll be getting out of it. So here's your overnight success story in a nutshell. Every day is special, we just gotta make it that way.</em></p>
  </div>

  <%= source_helper("alert alert-primary") %>

  <% if !@side_bar_topics.nil? %>
    <%= render "topics/widget" %>
  <% end %>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/jaywad"><%= fa_icon "github"%></a></li>
      <li><a href="https://twitter.com/jaywad26"><%= fa_icon "twitter"%></a></li>
      <li><a href="https://www.instagram.com/jamalawd/"><%= fa_icon "instagram"%></a></li>
      <li><a href="https://www.linkedin.com/in/jaywad/"><%= fa_icon "linkedin"%></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    <%= link_to "View All Portfolio Items", portfolios_path %> |
    <a href="#">Back to top</a>
    </p>
    <a href="http://www.jaywad.com" class="text-muted">Jaywad.com </a><%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">The best way to learn "Coding" is definitely not reading tutorial books. What you should do first is to skim through video tutorials. You just need to learn the logic first, the best practices then get down and start working on it. It's very daunting in the beginning, and trust me, you WILL struggle. However, at the end of it, you will come out a coder.</p>
    <p>
      <% if logged_in?(:site_admin) %>
      <%= link_to "Create new Portfolio Item", new_portfolio_path, class: "btn btn-warning" %>
      <% end %>
      <%= link_to "Find Out More About Me", about_me_path, class: "btn btn-primary my-2" %>
      <%= link_to "My Blog", blogs_path, class: "btn btn-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="lead text-muted">Hey there! I’m <b>Jamal Awad</b>, the creator of this website. I am completely self-taught, with a lot left to learn. While I was learning tech skills, I uncovered a passion for teaching others.</p>
        <p class="lead text-muted">Since I began gaining valuable digital skills, I became able to make more money, pursue passions that I care about, and, ultimately, enjoy freedom and flexibility.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-inline social-links">
          <li class="list-inline-item"><a href="https://github.com/jaywad"><%= fa_icon "github"%></a></li>
          <li class="list-inline-item"><a href="https://twitter.com/jaywad26"><%= fa_icon "twitter"%></a></li>
          <li class="list-inline-item"><a href="https://www.instagram.com/jamalawd/"><%= fa_icon "instagram"%></a></li>
          <li class="list-inline-item"><a href="https://www.linkedin.com/in/jaywad/"><%= fa_icon "linkedin"%></a></li>
          <li class="list-inline-item"><p><a href="mailto:jamalawad26@gmail.com?subject=Portfolio Contact" "Email me"><%= fa_icon "at" %></a></li>
        </ul>
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <li><%= navbar_helper("text-white", "li") %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="/" class="navbar-brand d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
        <%= fa_icon "connectdevelop" %>
        </svg>
      <strong>Jamal AWAD</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>