config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  # now we can create our own show action since we used except up
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # added route in data management section - scope
  get 'portfolios/angular-items', to: 'portfolios#angular'

  # get 'pages/home'
  root to: 'pages#home'

  # get 'pages/about'
  get 'about-me', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  get 'tech-news', to: 'pages#tech_news'

  post 'message', to: 'pages#message'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/pages/_contact_left.html.erb
<div class="sign-up">
  <div class="card">
    <div class="card-body">
      <h2>Send me a message</h2>
      <br>
      <%= form_for @message, url: message_path do |f| %>
        <div class="form-group">
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Name" %>
        </div>

        <div class="form-group">
          <%= f.email_field :email, autocomplete: "off", class: "form-control", placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= f.text_area :message, class: "form-control", placeholder: "How can I help?", rows: 6 %>
        </div>

        <div class="actions">
          <%= f.submit "Send Message", class: "btn btn-dark btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_contact_right.html.erb
<h3>Office Address</h3>

<p>Lebanon, Zahle (Bekaa Governorate)</p>

<h3>Mobile</h3>

<p><%= number_to_phone "9613701879" %></p>

<h3>Email</h3>

<p><a href="mailto:jamalawad26@gmail.com?subject=Portfolio Contact" "Email me">Email me</a></p>

app/views/pages/about.html.erb
<div class="app-card-container">
  <div class="card">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag "profile2.jpg", width: 300, class: "profile-img" %>

        <div class="skills">
          <% @skills.each do |skill| %>
            <h4><%= skill.title %></h4>
            <div class="progress">
              <div 
                class="progress-bar progress-bar-striped bg-success" 
                role="progressbar" 
                aria-valuenow="<%= skill.percent_utilized %>%"
                aria-valuemax="100"
                style="width: <%= skill.percent_utilized %>%"><%= skill.percent_utilized %>%
              </div>
            </div>
          <% end %>
        </div>
      </div>
      
      <div class="col-md-8">
        <h1>About Me</h1>
        <p>Creative and dedicated developer with over five years of professional experience in large international organizations in senior capacities which I thrived through my commitment to continuously discover, evaluate, and implement new technologies to maximize development efficiency.</p> 

        <p>My experience includes strong knowledge of project management, planning and control, database platforms, Ruby on Rails for back-end web development, AngularJS for front-end development, android mobile development, data security establishment and client-server networking hands on expertise.</p>


        <div id="accordion">
          <div class="card">
            <div class="card-header" id="headingTwo">
              <h5 class="mb-0">
                <button class="btn btn-dark collapsed" data-toggle="collapse" data-target="#education" aria-expanded="false" aria-controls="education">
                  Education
                </button>
              </h5>
            </div>
            <div id="education" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="card card-body">
                <b>Lebanese International University</b>
                Master's degree, Computer Software Engineering<br>
                <small class="text-muted">2015 • On-hold</small>
              </div>

              <div class="card card-body">
                <b>Lebanese International University</b>
                Bachelor of Science (BS), Computer Science<br>
                <small class="text-muted">2009 - 2013</small>
              </div>

              <div class="card card-body">
                <b>United Nations - UNRWA</b>
                High School Diploma - Lebanese Baccalaureate Life Science<br>
                <small class="text-muted">2008 - 2009</small>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-info" data-toggle="collapse" data-target="#jobHistory" aria-expanded="true" aria-controls="jobHistory">
                  Job History
                </button>
              </h5>
            </div>

            <div id="jobHistory" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card card-body">
                <div class="row">
                  <div class="col-md-2">
                    <%= image_tag "unhcr.jpg", width: "100%" %>
                  </div>
                  <div class="col-md-10">
                    <b>Assistant Data Management Officer (Cash)</b><br>
                    UNHCR<br>
                    <small class="text-muted">Apr 2016 - Present - Lebanon • <%= distance_of_time_in_words(Time.parse('2016-04-01'), Time.now) %></small>
                  </div>
                </div>
              </div>

              <div class="card card-body">
                <div class="row">
                  <div class="col-md-2">
                    <%= image_tag "unhcr.jpg", width: "100%" %>
                  </div>
                  <div class="col-md-10">
                    <b>Senior Data Management Assistant (Cash)</b><br>
                    UNHCR<br>
                    <small class="text-muted">May 2015 - Apr 2016 - Lebanon • 2 years</small>
                  </div>
                </div>
              </div>

              <div class="card card-body">
                <div class="row">
                  <div class="col-md-2">
                    <%= image_tag "drc.jpg", width: "100%" %>
                  </div>
                  <div class="col-md-10">
                    <b>Data Management Officer</b><br>
                    Danish Refugee Council<br>
                    <small class="text-muted">May 2013 - May 2014 - Lebanon • 1 year 1 mo</small>
                  </div>
                </div>
              </div>

              <div class="card card-body">
                <div class="row">
                  <div class="col-md-2">
                    <%= image_tag "rio.jpg", width: "100%" %>
                  </div>
                  <div class="col-md-10">
                    <b>Database Administrator</b><br>
                    RIO Trading<br>
                    <small class="text-muted">Aug 2012 - May 2013 - Lebanon • 10 mos</small>
                  </div>
                </div>
              </div>

              <div class="card card-body">
                <div class="row">
                  <div class="col-md-2">
                    <%= image_tag "rio.jpg", width: "100%" %>
                  </div>
                  <div class="col-md-10">
                    <b>Android Developer</b><br>
                    Freelance, self-employed<br>
                    <small class="text-muted">Jan 2011 - Dec 2012 - Lebanon • 2 years</small>
                  </div>
                </div>
              </div>

              <div class="card card-body">
                <div class="row">
                  <div class="col-md-2">
                    <%= image_tag "rio.jpg", width: "100%" %>
                  </div>
                  <div class="col-md-10">
                    <b>Project Manager</b><br>
                    Youth Council | مجلس الشباب<br>
                    <small class="text-muted">Sep 2015 - Mar 2016 - Lebanon • 7 mos</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header" id="headingThree">
              <h5 class="mb-0">
                <button class="btn btn-success collapsed" data-toggle="collapse" data-target="#projects" aria-expanded="false" aria-controls="projects">
                  Projects
                </button>
              </h5>
            </div>
            <div id="projects" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
              <div class="card card-body">
                <b>Loading...</b>
                <small class="text-muted">Great ideas are coming up soon 💻🌎</small><br>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<h1><span class="element"></span></h1>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= render "pages/contact_left" %>
    </div>
    <div class="col-md-6" style="padding-top: 100px">
      <%= render "pages/contact_right" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-6"></div>
  <div class="col-md-6">
    <main role="main" class="inner cover">
      <h1 class="cover-heading">Welcome to my online home.</h1>
      <p class="lead">Software development should not be a secret process. When I take on a new project I make it my goal not only to deliver a well crafted product but also to ensure that each stage of the process is fully communicated.</p>
      <p class="lead">
        <%= link_to "About Me", about_me_path, class: "btn btn-lg btn-secondary" %>
      </p>
    </main>
  </div>
</div>

app/views/pages/tech_news.html.erb
<div class="album py-5">
  <h1 class="cover-heading">Tech News</h1>
  <br>
  <br>
  <div class="container">
    <div class="row">
      <% @tweets.each do |tweet| %>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">          
            <div class="card-body tech-news">
              <p class="card-text">
                <%= twitter_parser tweet %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>